### ISSUE TITLE
Last section from reports dropped

### ISSUE THREAD

**Issue by wizjany** [EngineHub/enginehub-website#13]
https://github.com/EngineHub/enginehub-website/blob/860c55ba5f4c1225fafd002325a68c51ec1d129b/paste/src/views/ReportComponent.tsx#L76-L105

the final `currentSection` when the loop completes is never pushed to `sections`, so the final section (in e.g. `/wg report -p` it should be the applicable regions) will be missing from the formatted page despite being in the raw report.

**Comment by me4502** [comment]
Fixed.
